### ISSUE TITLE
服务器无法获取密钥，版本为1.12.2的CatServer

### ISSUE THREAD

**Issue by sdderfg** [DreamVoid/Whitelist4QQ#7]
[00:04:41] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[00:04:41] [DefaultDispatcher-worker-1/ERROR]: [MiraiMC] Failed to fetch ECDH public key from server, using default key instead
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at io.ktor.utils.io.bits.MemoryJvmKt.sliceSafe(MemoryJvm.kt:211) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.utils.io.bits.Memory.slice-SK3TCg8(MemoryJvm.kt:47) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.utils.io.charsets.CharsetJVMKt.encodeImpl(CharsetJVM.kt:356) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.utils.io.charsets.EncodingKt.encodeToImpl(Encoding.kt:204) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.utils.io.charsets.EncodingKt.encode(Encoding.kt:62) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.utils.io.charsets.EncodingKt.encode$default(Encoding.kt:57) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.CodecsKt.encodeURLParameter(Codecs.kt:123) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:68) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:67) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo$default(_Collections.kt:3341) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:67) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:108) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:90) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.URLUtilsKt.appendUrlFullPath(URLUtils.kt:101) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.URLUtilsKt.getFullPath(URLUtils.kt:79) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.http.Url.toString(URLBuilder.kt:169) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:183) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:71) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [mirai-core-all-2.10.0-RC2.jar:?]
[00:04:41] [nioEventLoopGroup-160-2/ERROR]: [MiraiMC] Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {353=[B@811fcd0}
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:188) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368) ~[mirai-core-all-2.10.0-RC2.jar:?]
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.10.0-RC2.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.10.0-RC2.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [SingleThreadEventExecutor.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [NioEventLoop.class:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [SingleThreadEventExecutor$5.class:4.1.24.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [FastThreadLocalRunnable.class:4.1.24.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/MiraiMC/issues
